name: Weekly Build and Release

on:
  schedule:
    # This will run every week at 00:00 UTC on Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Weekly Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfiles/sail-base
          platforms: linux/amd64,linux/arm64
          tags: |
            riscvintl/sail-base-image:${{ github.sha }}
            riscvintl/sail-base-image:latest
          push: ${{ github.event_name != 'pull_request' }}
